---
- name: install properties, example shell scripts, and environment variables
  become: yes
  become_user: root
  with_items:
    - f: producer.properties
      d: '{{kafka_install_parent_dir}}/kafka/config'
      m: '0644'
    - f: simple-test-create-topic.sh
      d: '{{kafka_install_parent_dir}}/kafka/bin'
      m: '0755'
    - f: simple-test-run-console-producer.sh
      d: '{{kafka_install_parent_dir}}/kafka/bin'
      m: '0755'
    - f: kafka-producer.sh
      d: /etc/profile.d
      m: '0644'
  template:
    src: '{{item.f}}.j2'
    dest: '{{item.d}}/{{item.f}}'
    mode: '{{item.m}}'
